### ISSUE TITLE
what should be in A and B dir of the datasets ?

### ISSUE THREAD

**Issue by flybirp** [duxingren14/DualGAN#1]
above

**Comment by duxingren14** [comment]
A could be maps, and B could be aerial photos of the same size.

Zili

**Comment by kickbox** [comment]
Can you please guide me as to where should I place A and B folders and how to pass their paths for my custom dataset?

**Comment by duxingren14** [comment]
--datasets
   --dbname
      --train
         --A
         --B
      --val
         --A
         --B

Please follow the readme instruction, use download_dataset.sh
<https://github.com/duxingren14/DualGAN/blob/master/datasets/download_dataset.sh>
to
download a sample dataset, and then look into details.

**Comment by TiAmo-one** [comment]
> --datasets --dbname --train --A --B --val --A --B 请按照 readme 说明，使用 download_dataset.sh < https://github.com/duxingren14/DualGAN/blob/master/datasets/download_dataset.sh > 下载示例数据集，然后查看详细信息。
> […](#)

It seems that the dataset cannot be downloaded now：

HaKan@DESKTOP-GLTKUF2 MINGW64 ~/Desktop/DualGAN-master
$ bash ./datasets/download_dataset.sh sketch-photo
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2025-04-07 17:30:05--  http://www.cs.mun.ca/~yz7241/dualgan/dataset/sketch-photo.zip
Resolving www.cs.mun.ca (www.cs.mun.ca)... 134.153.48.5
Connecting to www.cs.mun.ca (www.cs.mun.ca)|134.153.48.5|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2025-04-07 17:30:07 ERROR 403: Forbidden.

mkdir: cannot create directory ‘./datasets/sketch-photo/’: File exists
Archive:  ./datasets/sketch-photo.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ./datasets/sketch-photo.zip or
        ./datasets/sketch-photo.zip.zip, and cannot find ./datasets/sketch-photo.zip.ZIP, period.
