### ISSUE TITLE
How to use labeled data

### ISSUE THREAD

**Issue by daodaofr** [duxingren14/DualGAN#2]
I run with the argument --use_labeled_data 'semi', and got an error : 'AttributeError: 'DualNet' object has no attribute 'C_d_vars' .
I uncommented some code in the model.py, but still have problem running the code.
Please give me some advice. Thanks.

**Comment by daodaofr** [comment]
It's the problem of tensorflow version. The usage of tf.concat has changed, and the tf.mul no longer exists.
I am now running with labeled data.

Yet I have another question about your experiment settings. I've tried with your default setting (without labeled data) on facades datasets, and I train for 200 epochs, but the generation results are very blurry and are far away from the results in the paper. Can you give me some advice on the training params?

**Comment by duxingren14** [comment]
@daodaofr 
Please try the arguments as below:
facades-batch_sz_1-img_sz_256-fltr_dim_64-L2-fcn_1-lambda_ABp_100.0_200.0_200.0-c_0.01-n_critic_3-semi_False
Here ABp_100.0_200.0_200.0-c means alpha_A=100, alpha_B=200, alpha_p has been deprecated (you could set it to any value).

Please use "nosemi". Semi-supervised learning has been deprecated. I will update the code later.
