### ISSUE TITLE
A question in dualgan

### ISSUE THREAD

**Issue by JipengWuxmu** [duxingren14/DualGAN#20]
When i read dualgan, i meed a problem.
It‘s −DA(GB(v,z0))−DB(GA(u,z)) in formula 3,
can one task's discriminator used in another task's generator.

**Comment by duxingren14** [comment]
Thanks for pointing out that confusion. Oh, I checked out that it is an mistake. It should be −DB(GB(v,z0))−DA(GA(u,z)) . Great thanks.
