### ISSUE TITLE
Using custom datasets?

### ISSUE THREAD

**Issue by nobodykid** [duxingren14/DualGAN#24]
Hello, I'd like to ask if I can use custom datasets to train and test the model?

Currently, I had different dataset with different image size (126x126), but still had the same characteristics as your `sketch-photo` dataset (ie. having set A and B, both in `train` and `val` set)

I once tricked the model by filling the `val` directory of `sketch-photo` dataset with my own dataset, and it worked. I just want to know is there a way to do this by just providing my dataset without reconfiguring the `sketch-photo` dataset directories

**Comment by duxingren14** [comment]
Providing the correct format, customized dataset is definitely allowed.

**Comment by nobodykid** [comment]
I see, thank you for the help
