### ISSUE TITLE
Why is session run twice in the optimizer?

### ISSUE THREAD

**Issue by Cristy94** [duxingren14/DualGAN#7]
In [model.py](https://github.com/duxingren14/DualGAN/blob/a47fa76be9c899d010a3ea48cbc15989144b59b8/model.py#L179), why is the training step ran twice for the generators?

```
  def run_optim(self,batch_A_imgs, batch_B_imgs,  counter, start_time):
        _, Adfake,Adreal,Bdfake,Bdreal, Ad, Bd = self.sess.run(
            [self.d_optim, self.Ad_loss_fake, self.Ad_loss_real, self.Bd_loss_fake, self.Bd_loss_real, self.Ad_loss, self.Bd_loss], 
            feed_dict = {self.real_A: batch_A_imgs, self.real_B: batch_B_imgs})
        _, Ag, Bg, Aloss, Bloss = self.sess.run(
            [self.g_optim, self.Ag_loss, self.Bg_loss, self.A_loss, self.B_loss], 
            feed_dict={ self.real_A: batch_A_imgs, self.real_B: batch_B_imgs})

        _, Ag, Bg, Aloss, Bloss = self.sess.run(
            [self.g_optim, self.Ag_loss, self.Bg_loss, self.A_loss, self.B_loss], 
            feed_dict={ self.real_A: batch_A_imgs, self.real_B: batch_B_imgs})
```

In the paper it says:

> To optimize the DualGAN networks, we follow the training
procedure proposed in WGAN [1]; see Alg. 1. We train
the discriminators ncritic steps, then one step on generators

So, is the code doing the opposite (stepping generators twice and discriminator only once) ?

**Comment by duxingren14** [comment]
This cides has been revised to apply traditional GAN instead of WGAN. I will add some comments to resolve the confusion.

**Comment by rainsoulsrx** [comment]
I have the same doubts, would you please give more interpretation?
